# Simple workflow for deploying static content to Google Cloud Bucket
name: Render and Deploy to GCS

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # Single deploy job 
  render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Render links page
        uses: anthonynixon/links-template-render-github-action@v0.2.3
        with:
          template: "index.html.tmpl"
          values: "links.yaml"
          outputFile: "index.html"

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - run: gsutil -m rsync -d -c -r public gs://meta.earthisacube.com
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://meta.earthisacube.com/**/*.html
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://meta.earthisacube.com/js/*.js
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://meta.earthisacube.com/css/*.css
