# Simple workflow for deploying static content to GitHub Pages
name: Render links.ajn.me content

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  # Single deploy job since we're just deploying
  links-template-render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anthonynixon/links-template-render-github-action@v0.2.0
