# Simple workflow for deploying static content to Google Cloud Bucket
name: Render and Deploy to GCS

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # Single deploy job 
  render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Render links page
        uses: anthonynixon/links-template-render-github-action@v1.2.0
        with:
          template: "index.html.tmpl"
          values: "links.yaml"
          outputFile: "index.html"
          gitSHA: ${{ github.sha }}

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - run: gcloud storage cp index.html gs://links.ajn.me
      - run: gsutil -m rsync -d -c -r assets gs://links.ajn.me
      - run: gsutil -m rsync -d -c -r images gs://links.ajn.me
